### ISSUE TITLE
Fastest resource van be 0 bytes and 0 ms

### ISSUE THREAD

**Issue by soulgalore** [wesleyhales/speedgun#10]
When I'm testing http://www.cybercom I got a resource that is 0 bytes and 0 ms. That is incredible fast! 
Maybe we could just skip resources that are 0 bytes / 0 ms from the fastest resource list, because it seems in relevant?

Best
Peter

![fastest-resource](https://cloud.githubusercontent.com/assets/540757/6123385/3411e2e8-b102-11e4-8abd-2e149738985e.png)

**Comment by wesleyhales** [comment]
+1
