### ISSUE TITLE
LoadEventEnd is not catched for some sites?

### ISSUE THREAD

**Issue by soulgalore** [wesleyhales/speedgun#11]
I've tested for the main newspaper in Sweden: http://www.aftonbladet.se

And I didn't get any page load time:
http://speedgun.io/#?uuid=c292df23-3cc2-4d95-b243-ed66561ca5fb

When I test in Chrome the loadEventEnd is fired. Could be a bug somewhere?

Best
Peter

**Comment by wesleyhales** [comment]
Yeah, I experience stuff like this a lot. I'm not sure how stable the nav timing api is in Phantom2, or if the events just aren't getting picked up. Need a simple test case.

**Comment by soulgalore** [comment]
I'll check this tomorrow, can compare it with the implementation I have in sitespeed.io and see if we got the same problem (I haven't tested it so much).

**Comment by wesleyhales** [comment]
Great!

**Comment by soulgalore** [comment]
Hey @wesleyhales , the good news is that I know what's wrong, the bad news is that I haven't fixed it :) 

When I looked at the code, I remembered that I had the same problem before. The performance object isn't populated when page.evaluate is run (or rather not all of the values). I've used the waitFor example in phantomjs and just wait for the loadEventEnd to happen <code>window.performance.timing.loadEventEnd > 0</code>, you can check the implementation here:
https://github.com/sitespeedio/sitespeed.io/blob/master/lib/headless/scripts/collectTimings.js#L199

I've tested with the waitFor and it works every time. I could have a go at it later this week (but I guess it need some restructuring) or if you want to do it?

**Comment by wesleyhales** [comment]
@soulgalore you rock sir! thanks so much for the tip!

**Comment by soulgalore** [comment]
@wesleyhales :blush:
