### ISSUE TITLE
Rearrange the order of the metrics

### ISSUE THREAD

**Issue by soulgalore** [wesleyhales/speedgun#13]
I think like this:
The most important metrics first, making it easier for people to see the important things. Then it's just the hard part defining what's most important :)

I like that page load and perceived are in top, but then I would move up slowest and fastest assets. Then I would hide things like *Unload Event Start*, *Redirect start*, *navEvents* etc and make it possible to show them only if you want. 

Best
Peter

**Comment by wesleyhales** [comment]
Agree, similar to #7 but this provides more detail.

**Comment by wesleyhales** [comment]
I made a stab at this on the 1.0.0 release. Feel free to imrove
