### ISSUE TITLE
Running speedgun.js is too complicated.

### ISSUE THREAD

**Issue by wesleyhales** [wesleyhales/speedgun#15]
It should be an executable shortcut (see CasperJS). An obvious solution is to make it npm install-able.

**Comment by wesleyhales** [comment]
Examples where a better cli would replace my current arg lookup:
* https://github.com/wesleyhales/speedgun/blob/master/core/speedgun.js#L748
* https://github.com/wesleyhales/speedgun/blob/master/core/speedgun.js#L788
* https://github.com/wesleyhales/speedgun/blob/master/core/speedgun.js#L1032

**Comment by soulgalore** [comment]
yep will start looking at it today.

**Comment by soulgalore** [comment]
yep so installing via npm works fine now. I can have a look later at the problematic config.json file to check how we can solve that. Also would be nice to polish the output and start adding verbose logging:
<pre>
 $ speedgun http://speedgun.io
:::::::::::calling entrypoint: load
:::::::::::assign  [object Object] onInitialized
:::::::::::assign  [object Object] onLoadStarted
:::::::::::assign  [object Object] onLoadFinished
:::::::::::assign  [object Object] onNavigationRequested
:::::::::::assign  [object Object] onPageCreated
:::::::::::assign  [object Object] onResourceRequested
:::::::::::assign  [object Object] onResourceReceived
###### onLoadStarted 
###### onInitialized http://speedgun.io/
Print report running with timestamp:  
Rendering Screenshot to reports/http_speedgun.io/1423832770396.png
Writing report data to:  reports/http_speedgun.io/speedgun-json.json
!!exit phantom!!
</pre>

I can do that if the cli looks ok.

**Comment by wesleyhales** [comment]
cli looks great! thanks!
