### ISSUE TITLE
The width is broken on the start page for a Iphone

### ISSUE THREAD

**Issue by soulgalore** [wesleyhales/speedgun#9]
Everything looks ok on the start page with the text and the design, however something is breaking it because you can scroll to the right and get a big white area.

I'm using an Iphone 5 and Safari with iOS 8.1.1.

Checkout the monster image :)

![iphone-tothe-right 1](https://cloud.githubusercontent.com/assets/540757/6123352/79099496-b101-11e4-8122-f1e5dde3799c.png)

Best
Peter

**Comment by wesleyhales** [comment]
There's some text runoff somewhere below.
